### PR TITLE
Added system name on the game list where metadata is visible

### PR DESCRIPTION
**Pull request by rexmont**
Added a label on the game list underneath the game art to display the system name so that while searching the collections users can identify which system a game belongs to.

### CODE REVIEW

**Comment by anthonycaccese** [comment]
One alternative option we can try is updating `systemNameSuffix` on the textlist component in theme.xml to... 
`<systemNameSuffix>true</systemNameSuffix>`

That will turn on the display of system name abbreviations only on collections (both auto and custom ones).  And also work on all variant types (art and art + metadata)

It would look like this:
Screenshot 2024-04-10 at 10 59 09 AM

So pros I think are its super easy to implement and will work across all list variant types + it will only show on collections (so its not repeated info on a direct system)

What do you think of this instead?  We can also explore another option thats a bit more complex but wanted your feedback on this first.

**Comment by rexmont** [comment]
Hi @anthonycaccese, I think the solution you are proposing is perfect. Very clean and easy to implement, and proven it will work properly.

**Comment by anthonycaccese** [comment]
awesome, ok i'll close this PR then and make that change directly.  Will post back when its implemented.

**Comment by anthonycaccese** [comment]
Done!

**Comment by rexmont** [comment]
Awesome, thanks a mil!

**Pull request closed without merging**
